config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "products#index"
  resources :products do
      resources :reviews, except: [:index, :new , :show]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews
  
validates :name, :description , :price_in_cents, presence: true
validates :price_in_cents, numericality: { only_integer: true }

  def price_in_dollars
    price_in_dollars = price_in_cents.to_f/ 100
    sprintf("$%.2f", price_in_dollars)
  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  validates :comment, :rating , presence: true
  validates :rating , numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def index
		@products = Product.all
	end

	def show
	 @product = Product.find(params[:id])
	 @review = Review.new
	end


	def new
		@product = Product.new
	end

	def create
		@product = Product.new

		@product.name = params[:product][:name]
		@product.description = params[:product][:description]
		@product.price_in_cents = params[:product][:price_in_cents]

		if @product.save
			flash[:notice] = "You have successfully added #{@product.name} "
			redirect_to "/products"
		else
			render :new
		end
	end

	def destroy
		@product = Product.find(params[:id])
		@product.destroy
		flash[:notice] = "You have successfully deleted #{@product.name} "
		redirect_to "/products"

	end

	def edit
		@product = Product.find(params[:id])
	end

	def update
		@product = Product.find(params[:id])

		@product.name = params[:product][:name]
		@product.description = params[:product][:description]
		@product.price_in_cents = params[:product][:price_in_cents]

		if @product.save
			flash[:notice] = "You have successfully changed #{@product.name} "
			redirect_to "/products/#{@product.id}"
		else
			render :edit
		end
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
  end

  def show
   @review = Review.find(params[:id])
  end

  def create
    @product =Product.find(params[:product_id])
    @review = @product.reviews.new #associates the two common elements of the join table (the foreign key)
    #  that way they can connect and the reviews can properly show on the product show page.
    @review.comment = params[:review][:comment]
    @review.rating = params[:review][:rating]


    if @review.save
      flash[:notice] = "You have successfully added a review "
      redirect_to "/products/#{@product.id}"
    else
      render "/products/show"
    end

  end

  def destroy
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    @review.destroy
    flash[:notice] = "You have successfully deleted the review "
    redirect_to "/products"
  end

  def edit
    @product= Product.find(params[:product_id])
    @review = Review.find(params[:id])

  end

  def update
    @product= Product.find(params[:product_id])
    @review = Review.find(params[:id])
    @review.comment = params[:review][:comment]
    @review.rating= params[:review][:rating]

    if @review.save
      flash[:notice] = "You have successfully changed your review"
      redirect_to "/products/#{@product.id}"
    else
      render :edit
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rainforest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button type="button" class="btn btn-primary">
    Rain <span class="badge badge-light">Forest</span>
  </button>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/products/new">New Product</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

    <%= flash[:notice]%>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |f|%>

<p><%= f.label :name %>
<%= f.text_field :name %> </p>

<p><%= f.label :description%>
<%= f.text_field :description%> </p>

<p><%= f.label :image %>
<%= f.text_field :image %> </p>

<p><%= f.label :"price_in_cents " %>
<%= f.text_field :price_in_cents%></p>
<%=f.submit class: "btn btn-primary" %>

<%end%>

app/views/products/edit.html.erb
<%= render "form"%>
<%= link_to("show","/products/#{@product.id}") %>

app/views/products/index.html.erb
<h1> Welcome to Rainforest! </h1>

<h2> Our Products</h2>


<div class="container">
  <div class="row">
  <% @products.each do |product| %>
    <div class="col-sm">
      <div class="card" style="width: 20rem;">
          <div class="card-body">
            <%=image_tag(product.image, width: 200, height: 190)%><br>
            <strong>Product Name:</strong> <%= product.name %><br/>
            <strong>Description:</strong> <%= product.description%><br/>
            <strong>Price:</strong> <%= product.price_in_dollars %><br />
            <button type="button" class="btn btn-success"><%= link_to("#{product.name}","/products/#{product.id}") %></a>
          </div>
    </div>
  </div>
  <% end%>
</div><br>
</div>

app/views/products/new.html.erb
<% if @product.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@product.errors.count, "error") %> prohibited this from being saved:</h2>

		<ul>
		<% @product.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

<%= render "form"%>

app/views/products/show.html.erb
<p><b> Name:</b> <%= @product.name%> <br> <b> Description:</b> <%=@product.description %>
    <br><b> Price:</b><%=@product.price_in_dollars %> <br> product.id :<%= @product.id%>
    </p>

  <%= link_to("Edit","/products/#{@product.id}/edit")%>

  <%= link_to("Delete", "/products/#{@product.id}", method: :delete, data: {confirm: "Are you sure you want to delete this product?"})%>

    <h4>New review </h4>

    <%= render "/reviews/form.html.erb"%>
      <!--get the current product then get all the current reviews for it , look at products controller to ensure other data base is connected (see @review) -- >
      <!--
      - Get current product as @product
      - Get all reviews for this product using .reviews method
      - Loop over reviews
      -->
    <ul>
      <% @product.reviews.each do |review| %>
      <p>
        <strong>Comment:</strong> <%= review.comment %><br/>
        <strong>Rating</strong> <%= review.rating%> <%= review.id%><br>
      </p>
      <%= link_to "Edit review", edit_product_review_path(@product,review)%>
      <% end%>

    </ul>

app/views/reviews/_form.html.erb
<%= form_for([@product, @review]) do |f| %>
	<% if @review.errors.any? %>
		<div id ="error explaination">
			<h2><%= pluralize(@review.errors.count,"error")%> prohibited this review from being saved  </h2>

			<ul>
				<%@review.errors.full_messages.each do |msg| %>
					<li> <%= msg %> </li>
					<% end %>
			</ul>
		</div>
	<% end %>

	<div class= "field">
		<%=f.label :comment %>
		<%=f.text_area :comment %>
	</div>

<div class= "field">
<%=f.label :rating %>
<%=f.number_field :rating%>
</div>

	<div class "actions">
		<%=f.submit %>
	</div>
<% end %>

app/views/reviews/edit.html.erb
<h1> Edit comment </h1>
<%= render 'form'%>
<%= link_to("Delete", product_review_path(@product,@review), method: :delete, data: {confirm: "Are you sure you want to delete this product?"})%>